#!/usr/bin/env node
// @ts-check
/**
 * Generates src/manifest.generated.ts (the `Manifest` type) from the JSON Schema in
 * src/manifest-v1.schema.json. The output is checked in; run this after every schema edit:
 *
 *   pnpm --filter @harness-store/manifest generate
 *
 * `--check` compares instead of writing and exits 1 when the checked-in file is stale;
 * `pnpm typecheck` and the test suite both run it, so drift fails CI.
 * `--out <file>` writes to (or checks) another file; only the tests use it.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { compile } from 'json-schema-to-typescript';
import * as prettier from 'prettier';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const schemaPath = fileURLToPath(new URL('../src/manifest-v1.schema.json', import.meta.url));
const defaultOutPath = fileURLToPath(new URL('../src/manifest.generated.ts', import.meta.url));

const BANNER = `/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * The Manifest type, generated by scripts/generate-types.mjs from src/manifest-v1.schema.json.
 * Change the schema, then run \`pnpm --filter @harness-store/manifest generate\`.
 * \`pnpm typecheck\` fails while this file is out of date.
 */`;

/**
 * Renders the TypeScript source for the schema, formatted like the rest of the repository.
 * @param {string} outPath file the source is destined for (selects the Prettier config)
 * @returns {Promise<string>}
 */
async function render(outPath) {
  const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
  // Top-level `x-` keys are Publisher-private: validateManifest() drops them from the Manifest
  // it returns, so the type deliberately has no `[k: string]: unknown` index signature for them.
  delete schema.patternProperties;
  const source = await compile(schema, 'Manifest', {
    bannerComment: BANNER,
    // Objects in the schema are closed unless they say otherwise.
    additionalProperties: false,
    // Emit `T[]`, not unions of tuples, for minItems/maxItems.
    ignoreMinAndMaxItems: true,
    // Every $ref is local (#/$defs/...); never resolve anything over the network or disk.
    $refOptions: { resolve: { external: false } },
    format: false,
  });
  const config = (await prettier.resolveConfig(outPath)) ?? {};
  return prettier.format(source, { ...config, filepath: outPath });
}

const { values } = parseArgs({
  options: {
    check: { type: 'boolean', default: false },
    out: { type: 'string' },
  },
});
const outPath = values.out ?? defaultOutPath;
const expected = await render(outPath);
const shownPath = relative(packageRoot, outPath);

if (values.check) {
  const actual = await readFile(outPath, 'utf8').catch(() => '');
  if (actual !== expected) {
    console.error(
      `${shownPath} is out of date with src/manifest-v1.schema.json.\n` +
        'Run `pnpm --filter @harness-store/manifest generate` and commit the result.',
    );
    process.exit(1);
  }
  console.log(`${shownPath} matches the schema.`);
} else {
  await writeFile(outPath, expected);
  console.log(`Wrote ${shownPath}.`);
}
