/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * The Manifest type, generated by scripts/generate-types.mjs from src/manifest-v1.schema.json.
 * Change the schema, then run `pnpm --filter @harness-store/manifest generate`.
 * `pnpm typecheck` fails while this file is out of date.
 */

export type Tag =
  | 'coding'
  | 'writing'
  | 'research'
  | 'data'
  | 'productivity'
  | 'devops'
  | 'design'
  | 'education'
  | 'fun'
  | 'other';
export type Platform =
  'darwin-arm64' | 'darwin-x64' | 'win32-x64' | 'win32-arm64' | 'linux-x64' | 'linux-arm64';
/**
 * The command the Runtime executes. `node`: a relative path to a .js, .mjs or .cjs file. `binary`: an object mapping every declared platform to the relative path of an executable.
 */
export type Entry =
  | string
  | {
      'darwin-arm64'?: RelativePath;
      'darwin-x64'?: RelativePath;
      'win32-x64'?: RelativePath;
      'win32-arm64'?: RelativePath;
      'linux-x64'?: RelativePath;
      'linux-arm64'?: RelativePath;
    };
/**
 * Path of a file inside the Harness Package, relative to the archive root, with `/` separators and no `.` or `..` segments.
 */
export type RelativePath = string;
export type ModelId = string;
export type Domain = string;

/**
 * manifest.json at the root of a Harness Package, manifestVersion 1. Normative prose: docs/tech/manifest-spec.md.
 */
export interface Manifest {
  /**
   * Version of this Manifest format. This schema describes version 1 only.
   */
  manifestVersion: 1;
  /**
   * Harness ID, `publisher/slug`. The publisher segment is the Publisher's GitHub login, lower-cased. Immutable for the life of the Harness.
   */
  id: string;
  /**
   * Harness Version: strict semver (MAJOR.MINOR.PATCH with an optional pre-release, no build metadata). Must be greater than every previously published version.
   */
  version: string;
  /**
   * Display name, 2 to 40 characters.
   */
  name: string;
  /**
   * One sentence shown in lists, at most 120 characters.
   */
  summary: string;
  /**
   * At most 5 tags from the curated list, without duplicates.
   *
   * @maxItems 5
   */
  tags?: Tag[];
  /**
   * SPDX license identifier (e.g. `MIT`) or `proprietary`.
   */
  license: string;
  /**
   * Absolute http(s) URL of the Harness's homepage, without a user name or password.
   */
  homepage?: string;
  /**
   * Absolute http(s) URL of the source repository, without a user name or password, shown as "Source" on the detail page.
   */
  sourceRepo?: string;
  /**
   * Channel. Only `stable` exists in P0; `beta` is reserved for P1.
   */
  channel?: 'stable';
  /**
   * Non-empty list of the platforms the Harness runs on, without duplicates.
   *
   * @minItems 1
   */
  platforms: Platform[];
  runtime: HarnessRuntime;
  entry: Entry;
  ui: UserInterface;
  /**
   * Whether the Harness asks the User for a Workspace at launch.
   */
  workspace?: 'required' | 'optional' | 'none';
  models: Models;
  permissions: DeclaredPermissions;
  /**
   * Markdown for this version, at most 5 KB (5 120 bytes of UTF-8).
   */
  changelog?: string;
}
/**
 * What the Harness needs from the Runtime to start. `node`: the Runtime runs `entry` with its bundled Node 22. `binary`: the Harness ships its own executables.
 */
export interface HarnessRuntime {
  kind: 'node' | 'binary';
  /**
   * Node major the Runtime supplies. Required when kind is `node`; only `22` exists in P0.
   */
  node?: '22';
}
/**
 * UI Kind and its options. `path`, `readyTimeoutSeconds` and `window` apply to `web` only.
 */
export interface UserInterface {
  kind: 'web' | 'terminal';
  /**
   * Path the Runtime opens on the Harness's local server. Starts with a single `/`.
   */
  path?: string;
  /**
   * Seconds the Runtime waits for the port to accept connections.
   */
  readyTimeoutSeconds?: number;
  window?: WindowHints;
}
/**
 * Initial window size hints, in pixels.
 */
export interface WindowHints {
  width?: number;
  height?: number;
}
/**
 * The Model Slots the Harness uses.
 */
export interface Models {
  slots: ModelSlots;
}
/**
 * Model Slots by name. `default` is mandatory; at most 8 Slots.
 */
export interface ModelSlots {
  default: ModelSlot;
  [k: string]: ModelSlot;
}
/**
 * A Model Slot. The Harness asks the Model Gateway for it by name; the User decides which model fills it.
 */
export interface ModelSlot {
  /**
   * What the Harness uses this Slot for.
   */
  description?: string;
  requirements?: ModelRequirements;
  /**
   * Recommended Models, in preference order: at most 5 `provider/model` ids, without duplicates.
   *
   * @maxItems 5
   */
  recommended?: ModelId[];
}
/**
 * Model Requirements: what the Model Slot needs from a model. An absent key means no requirement.
 */
export interface ModelRequirements {
  tools?: boolean;
  /**
   * Minimum context window, in tokens.
   */
  minContext?: number;
  vision?: boolean;
  json?: boolean;
}
/**
 * Declared Permissions. All three keys are required. Informational in P0: shown for consent, not enforced.
 */
export interface DeclaredPermissions {
  filesystem: FilesystemPermission;
  /**
   * Whether the Harness executes commands.
   */
  shell: boolean;
  network: NetworkPermission;
}
export interface FilesystemPermission {
  /**
   * `none`: only its Data Directory. `workspace`: the chosen Workspace. `home`: anywhere under the User's home. `paths`: the listed paths.
   */
  scope: 'none' | 'workspace' | 'home' | 'paths';
  /**
   * At most 20 explicit paths (`~` allowed) of at most 1024 characters each, without duplicates. Required and non-empty when scope is `paths`.
   *
   * @maxItems 20
   */
  paths?: string[];
}
/**
 * Either `domains` (a list, possibly empty) or `any: true`. Traffic to the Model Gateway is implied and not declared.
 */
export interface NetworkPermission {
  /**
   * At most 20 lower-case domain names, optionally prefixed with `*.`, without duplicates.
   *
   * @maxItems 20
   */
  domains?: Domain[];
  any?: true;
}
